# Codecov Configuration for chrome-dev-assist

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 2%
        if_not_found: success

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false

# Ignore test files and generated code
ignore:
  - "tests/**/*"
  - "**/*.test.js"
  - "**/node_modules/**"
  - "**/coverage/**"
  - "**/*.config.js"
  - ".github/**"
  - "scripts/**"
  - "docs/**"

github_checks:
  annotations: true
