name: ❓ Question
description: Ask a question about usage or implementation
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What have you tried so far?
      placeholder: I tried X but got Y...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched existing issues
          required: true
